
--PROC_GERA_NF
--TABELAS ORIGEM PED_VENDAS, PED_VENDAS_ITENS, PED_COMPRAS, PED_COMPRAS_ITENS
--TABELAS DESTINO NOTA_FISCAL, NOTA_FISCAL_ITENS
--PARAMETROS @TIP_MOV,@DOCTO,@CFOP,@DATA_EMIS,@DATA_ENTREGA
--DROP  PROCEDURE PROC_GERA_NF 

--EXEC PROC_GERA_NF 'S',6,'5.101','2017-01-30','2017-01-30'
--EXEC PROC_GERA_NF 'E',2,'1.101','2017-01-30','2017-01-30'
CREATE PROCEDURE PROC_GERA_NF (@TIP_MOV AS CHAR(1),--E = ENTRADA S= SAIDA
                               @DOCTO INT,
							   @CFOP VARCHAR(5),
							   @DATA_EMIS DATE,
							   @DATA_ENTREGA DATE)
AS 
 BEGIN 
DECLARE @NOTA_TB TABLE
(
    NF  INT
)


DECLARE @DOCT INT,
        @NUM_NF INT,
		@ID INT,
		@COD_PAGTO INT,
		@NUM_PEDIDO INT,
		@SEQ_MAT INT,
		@COD_MAT INT,
		@QTD DECIMAL(10,2),
		@VAL_UNIT DECIMAL (10,2),
		@SUB_TOT_NFE DECIMAL(10,2),
		@TOTAL_NFE DECIMAL(10,2)

		SET @SUB_TOT_NFE=0
		SET @TOTAL_NFE=0 

BEGIN TRANSACTION

		IF (@DATA_EMIS>GETDATE() OR @DATA_ENTREGA>GETDATE())
		BEGIN
		PRINT 'NAO PERMITIDO LANCAMENTOS FUTUROS!' 
		END
		ELSE IF @TIP_MOV<>'S' AND @TIP_MOV<>'E'
		BEGIN 
		PRINT 'OPERACAO NAO PERMITIDA E CANCELADA!'
		END
		ELSE IF @TIP_MOV='S' AND (SELECT COUNT(*) FROM PEDIDO_VENDA A
		   WHERE A.NUM_PEDIDO=@DOCTO
		         AND A.SITUACAO<>'F')=0
		BEGIN 
		   PRINT 'NAO A PEDIDO DE VENDAS DISPONIVEL PARA SAIDA'
		END 
		ELSE IF @TIP_MOV='E' AND (SELECT COUNT(*) FROM PEDIDO_COMPRA A
		   WHERE A.NUM_PEDIDO=@DOCTO
		         AND A.SITUACAO<>'F')=0
		BEGIN 
		   PRINT 'NAO A PEDIDO DE COMPRAS DISPONIVEL PARA ENTRADA'
		END 
--INICIO NOTA FISCAL DE SAIDA
		ELSE IF @TIP_MOV='S' 
		BEGIN 
		
		DECLARE NOTA_FISCAL CURSOR FOR 

		SELECT A.NUM_PEDIDO,A.COD_CLIENTE,A.COD_PGTO
		FROM  PEDIDO_VENDA A
		WHERE A.NUM_PEDIDO=@DOCTO
		AND A.SITUACAO<>'F' --FINALIZADO

		OPEN NOTA_FISCAL
		FETCH NEXT FROM NOTA_FISCAL
		INTO @NUM_PEDIDO,@ID,@COD_PAGTO
		WHILE @@FETCH_STATUS = 0
			BEGIN
			INSERT INTO NOTA_FISCAL 
			OUTPUT INSERTED.NUM_NF INTO @NOTA_TB
			VALUES
			(@TIP_MOV,@CFOP,@ID,@COD_PAGTO,@DATA_EMIS,@DATA_ENTREGA,0,'N','N')
			PRINT @@ERROR
			SELECT @NUM_NF=NF FROM @NOTA_TB;
			--IMPRIMININDO CABECALHO
			SELECT @NUM_NF NUM_NF,@TIP_MOV TIP_MOV,@CFOP CFOP,@ID ID,@COD_PAGTO COD_PAGTO,
			@DATA_EMIS DAT_EMIS,@DATA_ENTREGA DATA_ENTREG

	--INICIO CURSRO DETALHES NFE
	--CURSOR DETALHE PED INICIO
	DECLARE NF_ITENS CURSOR FOR 
	SELECT A.SEQ_MATERIAL,A.COD_MATERIAL,A.QTD,A.VALOR_UNITARIO 
		FROM PEDIDO_VENDA_ITEM A
		WHERE A.NUM_PEDIDO=@DOCTO
		ORDER BY A.SEQ_MATERIAL

	OPEN NF_ITENS
		FETCH NEXT FROM NF_ITENS
		INTO @SEQ_MAT,@COD_MAT,@QTD,@VAL_UNIT
		WHILE @@FETCH_STATUS = 0
			BEGIN
			INSERT INTO NOTA_FISCAL_ITEM VALUES
			(@NUM_NF,@SEQ_MAT,@COD_MAT,@QTD,@VAL_UNIT,@DOCTO);
			PRINT @@ERROR
			--APRESENTANDO VALORES
			SELECT @NUM_NF NUM_NF,@SEQ_MAT SEQ ,@COD_MAT COD_MAT,@QTD QTD ,
			@VAL_UNIT VAL_UNIT,@DOCTO PED_ORIG
			--ATRIBUINDO VALORES
			SET @SUB_TOT_NFE=@QTD*@VAL_UNIT;
			SET @TOTAL_NFE=@TOTAL_NFE+@SUB_TOT_NFE;
			--SELECT @TOTAL_NFE
		FETCH NEXT FROM NF_ITENS
		INTO @SEQ_MAT,@COD_MAT,@QTD,@VAL_UNIT
		END
	  
		CLOSE NF_ITENS;
        DEALLOCATE NF_ITENS;
	--FINAL CURSOR DETALHES
	  
	   --ATUALIZANDO TOTAL NFE
		UPDATE NOTA_FISCAL SET TOTAL_NF=@TOTAL_NFE WHERE NUM_NF=@NUM_NF;
		--ATUALIZADO STATUS PARA FECHADO NFE
		UPDATE PEDIDO_VENDA  SET SITUACAO='F' WHERE NUM_PEDIDO=@DOCTO;

		FETCH NEXT FROM NOTA_FISCAL
		INTO @NUM_PEDIDO,@ID,@COD_PAGTO
	END
	--FINAL CURSOR NFE
	CLOSE NOTA_FISCAL;
    DEALLOCATE NOTA_FISCAL;
  END --END IF SAIDA
  --FIM NOTA FISCAL DE SAIDA
  --INICIO NOTA FISCAL ENTRADA
  ELSE IF @TIP_MOV='E' 
		BEGIN 
		
		DECLARE NOTA_FISCAL CURSOR FOR 

		SELECT A.NUM_PEDIDO,A.COD_FORNECEDOR,A.COD_PAGTO
		FROM  PEDIDO_COMPRA A
		WHERE A.NUM_PEDIDO=@DOCTO
		AND A.SITUACAO<>'F' --FINALIZADO

		OPEN NOTA_FISCAL
		FETCH NEXT FROM NOTA_FISCAL
		INTO @NUM_PEDIDO,@ID,@COD_PAGTO
		WHILE @@FETCH_STATUS = 0
			BEGIN
			INSERT INTO NOTA_FISCAL 
			OUTPUT INSERTED.NUM_NF INTO @NOTA_TB
			VALUES
			(@TIP_MOV,@CFOP,@ID,@COD_PAGTO,@DATA_EMIS,@DATA_ENTREGA,0,'N','N')
			PRINT @@ERROR
			SELECT @NUM_NF=NF FROM @NOTA_TB;
			--APRESENTANDO VALORES CABECALHO
			SELECT @NUM_NF NUM_NF,@TIP_MOV TIP_MOV,@CFOP CFOP,@ID ID,@COD_PAGTO COD_PAGTO,
			@DATA_EMIS DAT_EMIS,@DATA_ENTREGA DATA_ENTREG

	--INICIO CURSRO DETALHES NFE
	--CURSOR DETALHE PED INICIO
	DECLARE NF_ITENS CURSOR FOR 

	SELECT A.SEQ_MATERIAL,A.COD_MATERIAL,A.QTD,A.VALOR_UNITARIO 
		FROM PEDIDO_COMPRA_ITEM A
		WHERE A.NUM_PEDIDO=@DOCTO
		ORDER BY A.SEQ_MATERIAL

	OPEN NF_ITENS
		FETCH NEXT FROM NF_ITENS
		INTO @SEQ_MAT,@COD_MAT,@QTD,@VAL_UNIT
		WHILE @@FETCH_STATUS = 0
			BEGIN
			INSERT INTO NOTA_FISCAL_ITEM VALUES
			(@NUM_NF,@SEQ_MAT,@COD_MAT,@QTD,@VAL_UNIT,@DOCTO);
			PRINT @@ERROR
			--APRESENTANDO VALORES DO ITENS INSERIDOS
			SELECT @NUM_NF NUM_NF,@SEQ_MAT SEQ ,@COD_MAT COD_MAT,@QTD QTD ,@VAL_UNIT VAL_UNIT,@DOCTO PED_ORIG
			SET @SUB_TOT_NFE=@QTD*@VAL_UNIT;
			SET @TOTAL_NFE=@TOTAL_NFE+@SUB_TOT_NFE;
			--SELECT @TOTAL_NFE
		FETCH NEXT FROM NF_ITENS
		INTO @SEQ_MAT,@COD_MAT,@QTD,@VAL_UNIT
		
		END
	   
		CLOSE NF_ITENS;
        DEALLOCATE NF_ITENS;
	--FINAL CURSOR DETALHES

	 --ATUALIZANDO TOTAL NFE
		UPDATE NOTA_FISCAL SET TOTAL_NF=@TOTAL_NFE WHERE NUM_NF=@NUM_NF;
		--ATUALIZADO STATUS PARA FECHADO NFE
		UPDATE PEDIDO_COMPRA  SET SITUACAO='F' WHERE NUM_PEDIDO=@DOCTO;

		FETCH NEXT FROM NOTA_FISCAL
		INTO @NUM_PEDIDO,@ID,@COD_PAGTO
	END
	--FINAL CURSOR NFE
	CLOSE NOTA_FISCAL;
    DEALLOCATE NOTA_FISCAL;
  END
  --FIM NOTA FISCAL ENTRADA
 --VALIDACOES FINAIS
	IF @@ERROR <>0
	 BEGIN 
		ROLLBACK 
		PRINT 'OPERACAO CANCELADA'
	END
	ELSE
		BEGIN
		    PRINT 'OPERACAO FINALIZADA COM SUCESSO'
			COMMIT
		END

END --END PROCEDURE
   
/*
SELECT * FROM NOTA_FISCAL
SELECT * FROM NOTA_FISCAL_ITEM

SELECT * FROM PEDIDO_VENDA
SELECT * FROM PEDIDO_VENDA_ITEM
SELECT * FROM PEDIDO_COMPRA
SELECT * FROM PEDIDO_COMPRA_ITEM
*/