USE MINIERP
GO
--TRIGGER PRA BLOQUEAR USUARIO QUANDO DEMITIDO
CREATE TRIGGER TG_BLOQUEIA_USUARIO ON FUNCIONARIO    

AFTER UPDATE
AS
BEGIN

	DECLARE @MATRICULA INT
	DECLARE @DATE_DEMISS DATE

	SELECT @MATRICULA=INSERTED.MATRICULA,@DATE_DEMISS=INSERTED.DATE_DEMISSAO
	 FROM INSERTED;

 IF @DATE_DEMISS<>'1900-01-01'
	BEGIN
		UPDATE USUARIO SET SITUACAO='B' --BLOQUEIA
		WHERE MATRICULA=@MATRICULA;
		PRINT 'BLOQUEIO  DA MATRICULA '+CAST (@MATRICULA AS VARCHAR(20))+' REALIZADO COM SUCESSO';
	END
END


/*
TESTANDO
---------------------------------------------------
SELECT * FROM FUNCIONARIO
WHERE MATRICULA = 5

---------------------------------------------------
UPDATE FUNCIONARIO SET DATE_DEMISSAO='2017-06-03'
WHERE MATRICULA = 5

---------------------------------------------------
SELECT * FROM USUARIO

*/