--CRIAR UM LOGIN E PERMISSÕES NO BANCO
EXEC master.dbo.sp_addlogin 'UsrTeste','123'

--DCL CONCEDENDO ACESSO ATUALIZAÇÃO PARA UsrTeste
GRANT UPDATE ON FUNCIONARIOS TO UsrTeste;

--DCL CONCEDENDO ACESSO INSERIR PARA UsrTeste
GRANT INSERT ON FUNCIONARIOS TO UsrTeste;

--DCL CONCEDENDO ACESSO LEITURA PARA UsrTeste
GRANT SELECT ON FUNCIONARIOS TO UsrTeste;

--DCL CONCEDENDO ACESSO DELETE PARA UsrTeste
GRANT DELETE ON FUNCIONARIOS TO UsrTeste;