--CRIAR UM LOGIN E PERMISSÕES NO BANCO
EXEC master.dbo.sp_addlogin 'UsrTeste','123'
EXEC sp_grantdbaccess 'UsrTeste','UsrTeste'

--****** INICIO COMANDO GRANT ******

--DCL CONCEDENDO ACESSO ATUALIZAÇÃO PARA UsrTeste
GRANT UPDATE ON FUNCIONARIOS TO UsrTeste;

--DCL CONCEDENDO ACESSO INSERIR PARA UsrTeste
GRANT INSERT ON FUNCIONARIOS TO UsrTeste;

--DCL CONCEDENDO ACESSO LEITURA PARA UsrTeste
GRANT SELECT ON FUNCIONARIOS TO UsrTeste;

--DCL CONCEDENDO ACESSO DELETE PARA UsrTeste
GRANT DELETE ON FUNCIONARIOS TO UsrTeste;


--CRIAÇÃO DE PROCEDURE PARA TESTE
CREATE PROCEDURE procTeste
AS
SELECT * FROM cidades
--EXECUTAR PROCEDURE
EXEC procTeste

--DCL CONCEDENDO ACESSO PARA EXECUTAR PROCEDURE procTeste PARA UsrTeste
GRANT EXECUTE ON procTeste TO UsrTeste

--VERIFICANDO USUARIO LOGADO
SELECT CURRENT_USER

--ALTERANDO USUARIO LOGADO
SETUSER 'UsrTeste'


--****** INICIO COMANDO REVOKE ******

--DCL REVOGANDO ACESSO ATUALIZAÇÃO PARA UsrTeste
REVOKE UPDATE ON FUNCIONARIOS TO UsrTeste;

--DCL REVOGANDO ACESSO INSERIR PARA UsrTeste
REVOKE INSERT ON FUNCIONARIOS TO UsrTeste;

--DCL REVOGANDO ACESSO LEITURA PARA UsrTeste
REVOKE SELECT ON FUNCIONARIOS TO UsrTeste;

--DCL REVOGANDO ACESSO PARA EXECUTAR PROCEDURE procTeste PARA UsrTeste
REVOKE EXECUTE ON procTeste TO UsrTeste;


--****** INICIO COMANDO DENY ******

--DCL NEGANDO ACESSO ATUALIZAÇÃO PARA UsrTeste
DENY UPDATE ON FUNCIONARIOS TO UsrTeste;

--DCL NEGANDO ACESSO INSERIR PARA UsrTeste
DENY INSERT ON FUNCIONARIOS TO UsrTeste;

--DCL NEGANDO ACESSO LEITURA PARA UsrTeste
DENY SELECT ON FUNCIONARIOS TO UsrTeste;

--DCL NEGANDO ACESSO PARA EXECUTAR PROCEDURE procTeste PARA UsrTeste
DENY EXECUTE ON procTeste TO UsrTeste;