--CRIANDO TABELA CLIENTE PARA TESTE
use curso
CREATE TABLE cliente
(
	cod_cli		NCHAR(5) PRIMARY KEY,
	cli_nome	VARCHAR(50) NOT NULL
)

--INSERINDO REGISTROS NA TABELA CLIENTE APARTIR DE OUTRA TABELA
INSERT INTO cliente
SELECT CustomerID, CompanyName FROM NORTHWND.dbo.Customers

--CRIANDO TABELA PEDIDO PARA TESTE
CREATE TABLE pedido
(
	num_ped		INT PRIMARY KEY,
	cod_cliente	NCHAR(5) NOT NULL,
	data		DATETIME NOT NULL,
	total		DECIMAL(10,2)
)

--INSERINDO REGISTROS NA TABELA PEDIDO APARTIR DE OUTRA TABELA
INSERT INTO pedido (num_ped, cod_cliente, data)
SELECT OrderID, CustomerID, OrderDate FROM NORTHWND.dbo.Orders

--ATUALIZANDO CAMPO TOTAL DA TABELA PEDIDO COM UPDATE EM SUBSELECT
UPDATE pedido SET total = 
(
	SELECT SUM(d.UnitPrice*d.Quantity) FROM NORTHWND.dbo.[Order Details] d
	WHERE num_ped = d.OrderID
)