/* (REPLICATE) REPETE UMA CADEIA DE CARACTER NÚMERO REPETIDO DE VEZES */

--1° EXEMPLO
SELECT name,
	ProductLine,
	REPLICATE('0',4) + ProductLine AS 'Line Code' 
FROM Production.Product
WHERE ProductLine = 'T'
ORDER BY name

--2° EXEMPLO
use curso
CREATE TABLE t1
(
	c1 VARCHAR(3),
	c2 CHAR(3)
)

INSERT INTO t1 VALUES('2','2')
INSERT INTO t1 VALUES('37','37')
INSERT INTO t1 VALUES('597','597')

SELECT * FROM t1

SELECT 
	DATALENGTH(c1) AS dtlc1,
	DATALENGTH(c2) AS dtlc2,
	REPLICATE('0',3 - DATALENGTH(c1)) + c1 AS 'VARCHAR COLUNA',
	REPLICATE('0',3 - DATALENGTH(c2)) + c2 AS 'CHAR'
FROM t1


/* (LEFT) RETORNA UMA CADEIA DE CARACTERES A ESQUERDA */
use AdventureWorks2014

SELECT 
	name,
	LEFT(name, 6) AS 'Left Nome'
FROM Production.Product
ORDER BY ProductID 


/* (UPPER) PASSAR A CADEIA DE CARACTERES PARA MAIUSCULAS */
use curso

SELECT 
	estado,
	UPPER(estado) AS 'Upper Estado' 
FROM regiao_uf


/* (SUBSTRING) RETORNA A QUANTIDADE DE CARACTERES INFORMADA NA CONSULTA */
use AdventureWorks2014

SELECT
	 LastName,
	 SUBSTRING(LastName, 1,3) AS 'LastName 3 carac',
	 SUBSTRING(LastName, 4,9) AS 'LastName 9 carac'
FROM Person.Person
ORDER BY LastName


/* (REVERSE) RETORNA VALOR INVERTIDO DA CADEIA DE CARACTERES */
SELECT
	FirstName,
	REVERSE(FirstName) AS 'FirstName Reverso'
FROM Person.Person
WHERE BusinessEntityID < 5
ORDER BY FirstName