/* (CONVERT) FORMATAÇÃO DE DATA OU HORA 
 * ARQUIVO COM TODOS OS CÓDIGOS DE FORMATAÇÃO: Função Data Hora (Convert Código dos Formatos).pdf*/
SELECT
	CONVERT(VARCHAR(10),GETDATE(),103) 	AS [CONVERT 103 - 10],	-- DATA
	CONVERT(VARCHAR(5),GETDATE(),103)	AS [CONVERT 103 - 5],	-- DATA
	CONVERT(VARCHAR(10),GETDATE(),108) 	AS [CONVERT 108 - 10], 	-- HORA
	CONVERT(VARCHAR(5),GETDATE(),108)	AS [CONVERT 108 - 5],	-- HORA
	CONVERT(VARCHAR(20),GETDATE(),100)	AS [CONVERT 100 - 20]	-- DATA/HORA