-- (DATENAME) RETORNA DIA | MÊS NOME | ANO
SELECT 
	DATENAME (DAY, GETDATE()) 	AS DIA_N,
	DATENAME (MONTH, GETDATE()) AS MES_N,
	DATENAME (YEAR, GETDATE())	AS ANO_N


-- (DATEPART) RETORNA DIA | MÊS NÚMERO | ANO
SELECT 
	DATEPART (DAY, GETDATE())	AS DIA_P,
 	DATEPART (MONTH, GETDATE())	AS MES_P,
 	DATEPART (YEAR, GETDATE())	AS ANO_P
 
 	
-- (DATETIMEFROMPARTS) RETORNA DATA E HORA 7 ARGUMENTOS CONCATENADO 
 	
SELECT DATETIMEFROMPARTS(2021,09,08,16,27,2,5) AS DATA_HORA_CONC