-- (DATEADD) ADICIONA DIA OU MÊS OU ANO EM UM CAMPO DATA

-- ADICIONANDO 10 DIAS
SELECT 
	GETDATE() AS HOJE,
	DATEADD (DAY, 10, GETDATE()) AS [DIA+10] 
	
-- ADICIONANDO 2 MESES	
SELECT 
	GETDATE() AS HOJE,
	DATEADD (MONTH, 2, GETDATE()) AS [MÊS+2]

-- ADICIONANDO 6 ANOS
SELECT
	GETDATE() AS HOJE,
	DATEADD (YEAR, 6, GETDATE()) AS [ANO+6]
	
	
	
-- (DATEDIFF) RETORNA A DIFERENÇA EM QUANTIDADE EM DIA OU MÊS OU ANO

SELECT DATEDIFF(DAY, '1982-08-20',GETDATE()) AS QTDE_DIAS

SELECT DATEDIFF(MONTH , '1982-08-20',GETDATE()) AS QTDE_MES

SELECT DATEDIFF(YEAR, '1982-08-20',GETDATE()) AS QTDE_ANO	