use curso

--CONHECENDO AS TABELAS
SELECT * FROM cidades
SELECT * FROM senso_2013
SELECT * FROM uf
SELECT * FROM regiao_uf

/* (STDEV) RETORNA DESVIO PADRAO ESTATISTICO DE TODOS OS VALORES DA EXPRESSAO */
SELECT STDEV(populacao) FROM cidades

/* (STDEVP) RETORNA DESVIO PADRAO ESTATISTICO PARA POPULACAO DE TODOS OS VALORES DA EXPRESSAO */
SELECT STDEVP(populacao) FROM cidades

/* (GROUPING) AGRUPA TODOS OS VALORES E ADD COLUNA COM (0) NAO AGREGADO E (1) AGREGADO */
SELECT	uf,
		SUM(populacao)	AS SomaPopulacao,
		GROUPING(uf)	AS Grupo
FROM cidades
GROUP BY uf WITH ROLLUP -- COMANDO COMPLEMENTO DO GROUPING