/* MANIPULANDO TABELA TEMPORARIA
 * CRUD COM TEMP TABLE
 */
use curso

--CRIANDO TABELA TEMPORARIA
--1° EXEMPLO
CREATE TABLE #minhatbtemp
(
	campo1 VARCHAR(80) NOT NULL,
	campo2 MONEY NOT NULL
)

--INSERINDO DADOS NA TABELA TEMPORARIA
INSERT INTO #minhatbtemp VALUES ('REAL', 1000)
INSERT INTO #minhatbtemp VALUES ('DOLAR',3000)

--CONSULTANDO TABELA TEMPORARIA
SELECT * FROM #minhatbtemp


--CRIANDO TABELA TEMPORARIA
--2° EXEMPLO
SELECT * INTO #minhatbtemp2 FROM #minhatbtemp

--CONSULTANDO TABELA TEMPORARIA
SELECT * FROM #minhatbtemp2

--ATUALIZAÇÃO DE DADOS
UPDATE #minhatbtemp2 SET campo1 = 'LIBRA'
WHERE campo1  = 'REAL'

--EXCLUSÃO DOS REGISTROS
DELETE FROM #minhatbtemp2

--EXCLUSÃO DE TABELA
DROP TABLE #minhatbtemp2
