
--CRIANDO DATAWAREHOUSE
CREATE DATABASE MiniDW


--CRIACAO TABELAS DIMENSAO MATERIAL
CREATE TABLE D_MATERIAL
(
	COD_MAT int NOT NULL,
	DESCRICAO varchar(50) NOT NULL,
	PRECO_UNIT decimal(10, 2) NOT NULL,
	ID_FOR int NULL,
	DESC_TIP_MAT varchar(20) NOT NULL
)


--CRIACAO TABELA DIMENSAO CLIENTES
CREATE TABLE D_CLIENTES
(
	ID_CLIENTE int  NOT NULL,
	RAZAO_CLIENTE varchar(100) NOT NULL,
	TIPO_CLIENTE nchar(1) NULL,
	COD_CIDADE varchar(7) NOT NULL
) 


--CRIACAO TABELA DIMENSAO FORNECEDORES
CREATE TABLE D_FORNECEDORES
(
	ID_FOR int  NOT NULL,
	RAZAO_FORNEC varchar(100) NOT NULL,
	TIPO_FORNEC nchar(1) NULL,
	COD_CIDADE varchar(7) NOT NULL
)


--CRIACAO TABELAS DIMENSAO VENDEDORES
CREATE TABLE D_VENDEDORES
(
	ID_VEND int NOT NULL,
	MATRICULA int NOT NULL,
	NOME varchar(50) NOT NULL
)


--CRIACAO DA TABELAS DIMENSAO GERENTES
CREATE TABLE D_GERENTES
(
	ID_GER int NOT NULL,
	MATRICULA int NOT NULL,
	NOME varchar(50) NOT NULL
)


--CRIACAO TABELAS DIMENSAO CANAL VENDAS
CREATE TABLE D_CANAL_VENDAS
(
	ID_CLIENTE int NOT NULL,
	RAZAO_CLIENTE varchar(100) NOT NULL,
	ID_VEND int NOT NULL,
	NOME_VEND varchar(50) NOT NULL,
	ID_GER int NOT NULL,
	NOME_GER varchar(50) NOT NULL
)


--CRIACAO TABELA DIMENSAO PAGTO
CREATE TABLE D_COND_PAGTO
(
	COD_PAGTO int NOT NULL,
	NOME_CP varchar(50) NOT NULL,
	DIAS int NOT NULL,
	PCT decimal(10, 2) NOT NULL,
	PARC int NOT NULL
)


--CRIACAO TABELAS FATOS
--CRIACAO TABELA FATO DE FATUAMENTO
CREATE TABLE F_FATURAMENTO
(
	NUM_NF int NOT NULL,
	DATA_EMISSAO date NULL,
	ID_CLIENTE int NOT NULL,
	COD_MAT int NOT NULL,
	QTD int NOT NULL,
	VAL_UNIT decimal(10, 2) NOT NULL,
	TOTAL decimal(21, 2) NULL
)


--CRIACAO TABELA FATO CONTAS A RECEBER
CREATE TABLE F_CONTAS_RECEBER
(
	ID_DOC int NOT NULL,
	ID_CLIENTE int NOT NULL,
	PARC int NOT NULL,
	DATA_VENC date NOT NULL,
	DATA_PAGTO date NULL,
	VALOR decimal(10, 2) NULL,
	SITUACAO varchar(6) NOT NULL,
	MSG varchar(19) NOT NULL,
	DIAS_ATRASO int NULL
) 


--CRIACAO TABELA FATO CONTAS A PAGAR
CREATE TABLE F_CONTAS_PAGAR
(
	ID_DOC int NOT NULL,
	ID_FOR int NOT NULL,
	PARC int NOT NULL,
	DATA_VENC date NOT NULL,
	DATA_PAGTO date NULL,
	VALOR decimal(10, 2) NULL,
	SITUACAO varchar(6) NOT NULL,
	MSG varchar(19) NOT NULL
)


--CRIACAO TABELA FATO PED VENDAS
CREATE TABLE F_PED_VENDAS
(
	NUM_PEDIDO int  NOT NULL,
	ID_CLIENTE int NOT NULL,
	COD_PAGTO int NOT NULL,
	DATA_PEDIDO date NOT NULL,
	DATA_ENTREGA date NOT NULL,
	SITUACAO nchar(1) NOT NULL,
	TOTAL_PED decimal(10, 2) NULL
)


--CRIACAO TABELA FATO PED  COMPRAS
CREATE TABLE F_PED_COMPRAS
(
	NUM_PEDIDO int  NOT NULL,
	ID_FOR int NOT NULL,
	COD_PAGTO int NOT NULL,
	DATA_PEDIDO date NOT NULL,
	DATA_ENTREGA date NOT NULL,
	SITUACAO nchar(1) NOT NULL,
	TOTAL_PED decimal(10, 2) NULL
)


--CRIACAO TABELA FATO ESTOQUE
CREATE TABLE F_ESTOQUE
(
	COD_MAT int NOT NULL,
	QTD_SALDO decimal(10, 2) NOT NULL
) 


--CRIACAO DE TABELA FATO META
CREATE TABLE F_META_VENDA
(
	ID_VEND int NOT NULL,
	ANO varchar(4) NOT NULL,
	MES varchar(2) NOT NULL,
	VALOR decimal(10, 2) NULL
) 


--CRIACAO TABELAS FATO FATUR X META
CREATE TABLE F_META_VENDA_2017
(
	ID_VEND int NOT NULL,
	NOME_VEND varchar(50) NULL,
	ANO varchar(4) NOT NULL,
	MES varchar(2) NOT NULL,
	META decimal(10, 2) NULL,
	REALIZ decimal(38, 2) NULL,
	PCT decimal(10, 2) NULL
) 


--CRM FATO AGENDAS DETALHE
CREATE TABLE dbo.F_AGENDA_DETALHE
(
	ID_AGENDA int NOT NULL,
	MATRICULA int NOT NULL,
	NOME_VEND varchar(50) NOT NULL,
	RAZAO_CLIENTE varchar(100) NOT NULL,
	DATA_VISITA date NULL,
	SITUACAO char(1) NOT NULL,
	QTD_VISITAS int NOT NULL,
	GEROU_VENDA char(1) NOT NULL
) 


--CRM FATO AGENDAS RESUMO
CREATE TABLE dbo.F_AGENDAS_RESUMO
(
	MATRICULA int NOT NULL,
	NOME_VEND varchar(50) NOT NULL,
	RAZAO_CLIENTE varchar(100) NOT NULL,
	SITUACAO char(1) NOT NULL,
	QTD_VISITAS int NULL,
	GEROU_VENDA char(1) NOT NULL
)