--PROCEDURE DE CARGAR
--EXEC PROC_CARGA_DW
--CRIACAO DA PROC DE CARGA DW
USE MINIDW
GO

CREATE PROCEDURE PROC_CARGA_DW
AS
BEGIN
	PRINT 'CARGA INICIADA'

	-- ######################################## CARGA MATERIAL ########################################
	TRUNCATE TABLE  D_MATERIAL
	PRINT 'DADOS MATERIAL ELIMINADO'
	PRINT 'INICIO CARGA MATERIAL'
	PRINT GETDATE()

		INSERT INTO D_MATERIAL

			SELECT A.COD_MATERIAL,
				   A.DESCRICAO,
				   A.PRECO_UNITARIO,
				   A.COD_FORNECEDOR,
				   B.DESCRICAO 
	  
			FROM MINIERP.DBO.MATERIAL A
			INNER JOIN MINIERP.DBO.TIPO_MATERIAL B ON A.COD_TIPO_MATERIAL=B.COD_TIPO_MATERIAL

	PRINT 'FIM CARGA MATERIAL'
	PRINT GETDATE()


	-- ######################################## CARGA CLIENTE ########################################
	TRUNCATE TABLE D_CLIENTES
	PRINT 'DADOS CLIENTES ELIMINADOS'
	PRINT 'INICIO CARGA CLIENTES'
	PRINT GETDATE()

		INSERT INTO D_CLIENTES

			SELECT A.COD_CLIENTE,
					A.RAZAO_SOCIAL,
					A.TIPO_CLIENTE,
					A.COD_CIDADE
			FROM MINIERP.DBO.CLIENTE A

	PRINT 'FIM CARGA CLIENTES'
	PRINT GETDATE()


	-- ######################################## CARGA FORNECEDOR ########################################
	TRUNCATE TABLE D_FORNECEDORES
	PRINT 'DADOS FORNECEDORES ELIMINADOS'
	PRINT 'INICIO CARGA FORNECEDORES'
	PRINT GETDATE()

		INSERT INTO D_FORNECEDORES

			SELECT	A.COD_FORNECEDOR,
					A.RAZAO_SOCIAL,
					A.TIPO_FORNECEDOR,
					A.COD_CIDADE	 
			FROM MINIERP.DBO.FORNECEDOR A

	PRINT 'FIM CARGA FORNECEDORES'
	PRINT GETDATE()


	-- ######################################## CARGA VENDEDORES ########################################
	TRUNCATE TABLE D_VENDEDORES
	PRINT 'DADOS D_VENDEDORES ELIMINADOS'
	PRINT 'INICIO CARGA D_VENDEDORES'
	PRINT GETDATE()

		INSERT INTO D_VENDEDORES

			SELECT A.COD_VENDEDOR,
				   A.MATRICULA,B.NOME
			FROM MINIERP.DBO.VENDEDOR A
				INNER JOIN MINIERP.DBO.FUNCIONARIO B ON A.MATRICULA=B.MATRICULA

	PRINT 'FIM CARGA VENDEDORES'
	PRINT GETDATE()


	-- ######################################## CARGA GERENTES ########################################
	TRUNCATE TABLE D_GERENTES
	PRINT 'DADOS D_GERENTES ELIMINADOS'
	PRINT 'INICIO CARGA D_GERENTES'
	PRINT GETDATE()

		INSERT INTO D_GERENTES

			SELECT A.COD_GERENTE,
				   A.MATRICULA,B.NOME
			 FROM MINIERP.DBO.GERENTE A
				INNER JOIN MINIERP.DBO.FUNCIONARIO B ON A.MATRICULA=B.MATRICULA

	PRINT 'FIM CARGA D_GERENTES'
	PRINT GETDATE()


	-- ######################################## CARGA CANAL_VENDAS ########################################
	TRUNCATE TABLE D_CANAL_VENDAS
	PRINT 'DADOS D_CANAL_VENDAS ELIMINADOS'
	PRINT 'INICIO CARGA D_CANAL_VENDAS'
	PRINT GETDATE()
 
		INSERT INTO D_CANAL_VENDAS

			SELECT A.COD_CLIENTE,
				   A.RAZAO_SOCIAL,
				   A.ID_VEND,
				   A.NOME_VEND,
				   A.ID_GER,
				   A.NOME_GER
			 FROM MINIERP.DBO.V_CANAL_VENDAS A

	PRINT 'FIM CARGA V_CANAL_VENDAS'
	PRINT GETDATE()


	-- ######################################## CARGA CONDICOES DE PAGTO ########################################
	TRUNCATE TABLE D_COND_PAGTO
	PRINT 'DADOS D_COND_PAGTO ELIMINADOS'
	PRINT 'INICIO CARGA D_COND_PAGTO'
	PRINT GETDATE()

		INSERT INTO D_COND_PAGTO

			SELECT A.COD_CONDICAO_PGTO,
				   A.NOME_CONDICAO_PGTO,
				   B.DIAS,
				   B.PERCENTUAL,
				   B.PARCELA
			 FROM  MINIERP.DBO.CONDICAO_PGTO A
				 INNER JOIN MINIERP.DBO.CONDICAO_PGTO_DETALHE B ON A.COD_CONDICAO_PGTO=B.COD_CONDICAO_PGTO_DETALHE

	PRINT 'FIM CARGA D_COND_PAGTO'
	PRINT GETDATE()


	-- ######################################## CARGA FATURAMENTO ########################################
	TRUNCATE TABLE F_FATURAMENTO
	PRINT 'DADOS F_FATURAMENTO ELIMINADOS'
	PRINT 'INICIO CARGA F_FATURAMENTO'
	PRINT GETDATE()

		INSERT INTO F_FATURAMENTO

			SELECT A.NUM_NF,
				   A.DATA_EMISSAO,
				   A.COD_CLIFOR ID_CLIENTE,
				   A.COD_MATERIAL,
				   A.QTD,
				   A.VALOR_UNITARIO,
				   A.TOTAL
			FROM MINIERP.DBO.V_FATURAMENTO A

	PRINT 'FIM CARGA F_FATURAMENTO'
	PRINT GETDATE()


	-- ######################################## CARGA CONTAS RECEBER ########################################
	TRUNCATE TABLE F_CONTAS_RECEBER
	PRINT 'DADOS F_CONTAS_RECEBER ELIMINADOS'
	PRINT 'INICIO CARGA F_CONTAS_RECEBER'
	PRINT GETDATE()

		INSERT INTO F_CONTAS_RECEBER

			SELECT A.COD_DOC_ORIG,
				   A.COD_CLIENTE,
				   A.PARCELA,
				   A.DATA_VENCIMENTO,
				   A.DATA_PAGTO,
				   A.VALOR,
				   A.SITUACAO,
				   A.MSG,
				   A.DIAS_ATRASO
			FROM MINIERP.DBO.V_CONTAS_RECEBER A

	PRINT 'FIM CARGA F_CONTAS_RECEBER'
	PRINT GETDATE()


	-- ######################################## CARGA CONTAS PAGAR ########################################
	TRUNCATE TABLE F_CONTAS_PAGAR
	PRINT 'DADOS F_CONTAS_PAGAR ELIMINADOS'
	PRINT 'INICIO CARGA F_CONTAS_PAGAR'
	PRINT GETDATE()

		INSERT INTO F_CONTAS_PAGAR

			SELECT A.COD_DOC_ORIG,
				   A.COD_FORNECEDOR,
				   A.PARCELA,
				   A.DATA_VENCIMENTO,
				   A.DATA_PAGTO,
				   A.VALOR,
				   A.SITUACAO,
				   A.MSG  
			FROM MINIERP.DBO.V_CONTAS_PAGAR A

	PRINT 'FIM CARGA F_CONTAS_PAGAR'
	PRINT GETDATE()


	-- ######################################## CARGA PEDIDO VENDA ########################################
	TRUNCATE TABLE F_PED_VENDAS
	PRINT 'DADOS F_PED_VENDAS ELIMINADOS'
	PRINT 'INICIO CARGA F_PED_VENDAS'
	PRINT GETDATE() 

		INSERT INTO F_PED_VENDAS

			SELECT A.NUM_PEDIDO,
				   A.COD_CLIENTE,
				   A.COD_PGTO,
				   A.DATA_PEDIDO,
				   A.DATA_ENTREGA,
				   A.SITUACAO,
				   A.TOTAL_PED
			FROM MINIERP.DBO.PEDIDO_VENDA A
			   
	PRINT 'FIM CARGA F_PED_VENDAS'
	PRINT GETDATE()


	-- ######################################## CARGA PEDIDO COMPRAS ########################################
	TRUNCATE TABLE F_PED_COMPRAS
	PRINT 'DADOS F_PED_COMPRAS ELIMINADOS'
	PRINT 'INICIO CARGA F_PED_COMPRAS'
	PRINT GETDATE() 

		INSERT INTO F_PED_COMPRAS

			SELECT A.NUM_PEDIDO,
				   A.COD_FORNECEDOR,
				   A.COD_PAGTO,
				   A.DATA_PEDIDO,
				   A.DATA_ENTREGA,
				   A.SITUACAO,
				   A.TOTAL_PEDIDO
			FROM MINIERP.DBO.PEDIDO_COMPRA A
	   
	PRINT 'FIM CARGA F_PED_COMPRAS'
	PRINT GETDATE()


	-- ######################################## CARGA ESTOQUE ########################################
	TRUNCATE TABLE F_ESTOQUE
	PRINT 'DADOS F_ESTOQUE ELIMINADOS'
	PRINT 'INICIO CARGA F_ESTOQUE'
	PRINT GETDATE()

		INSERT INTO F_ESTOQUE

			SELECT A.COD_MATERIAL,
				   QTD_SALDO 
			FROM MINIERP.DBO.ESTOQUE A

	PRINT 'FIM CARGA F_ESTOQUE'
	PRINT GETDATE()


	-- ######################################## CARGA META ########################################
	TRUNCATE TABLE F_META_VENDA
	PRINT 'DADOS F_META_VENDA ELIMINADOS'
	PRINT 'INICIO CARGA F_META_VENDA'
	PRINT GETDATE()

		INSERT INTO F_META_VENDA

			SELECT  A.COD_VENDEDOR,
					A.ANO,
					A.MES,
					A.VALOR
			FROM MINIERP.DBO.META_VENDA A

	PRINT 'FIM CARGA F_META_VENDA'
	PRINT GETDATE()

	-- ######################################## CARGA META X FATO 2017 ########################################
	TRUNCATE TABLE F_META_VENDA_2017
	PRINT 'DADOS F_META_VENDA_2017 ELIMINADOS'
	PRINT 'INICIO CARGA F_META_VENDA_2017'
	PRINT GETDATE()

		INSERT INTO F_META_VENDA_2017

			SELECT A.COD_VENDEDOR,
			   B.NOME_VEND,
			   A.ANO,
			   A.MES,
			   A.VALOR META,
			   SUM(ISNULL(C.TOTAL,0)) REALIZ,
			   CAST(100/A.VALOR*SUM(ISNULL(C.TOTAL,0)) AS DECIMAL(10,2)) PCT	 
			FROM MINIERP.DBO.META_VENDA A
				LEFT JOIN MINIERP.DBO.V_CANAL_VENDAS B ON A.COD_VENDEDOR=B.ID_VEND
				LEFT JOIN  MINICRM.DBO.V_CRM_FAT_RESUMO C ON B.COD_CLIENTE=C.COD_CLIFOR
				AND A.MES=C.MES
				AND A.ANO=C.ANO
			WHERE A.ANO=2017
			GROUP BY A.COD_VENDEDOR,
					B.NOME_VEND,
					A.ANO,
					A.MES,
					A.VALOR,	
					100/A.VALOR				

	PRINT 'FIM CARGA F_META_VENDA_2017'
	PRINT GETDATE()


	-- CRM ##################################### CARGA AGENDAS RESUMO ########################################
	TRUNCATE TABLE F_AGENDAS_RESUMO
	PRINT 'DADOS F_AGENDAS_RESUMO ELIMINADOS'
	PRINT 'INICIO CARGA F_AGENDAS_RESUMO'
	PRINT GETDATE()

		INSERT INTO F_AGENDAS_RESUMO

			SELECT A.MATRICULA,
				   A.NOME_VEND,
				   A.RAZAO_SOCIAL,
				   A.SITUACAO,
				   A.QTD_VISITAS,
				   A.GEROU_VENDA 
			FROM MINICRM.DBO.V_CRM_AGENDAS_RESUMO A
	
		PRINT 'FIM CARGA F_AGENDAS_RESUMO'
		PRINT GETDATE()


	-- CRM ##################################### CARGA AGENDA DETALHE ########################################	   
	TRUNCATE TABLE F_AGENDA_DETALHE
	PRINT 'DADOS F_AGENDA_DETALHE ELIMINADOS'
	PRINT 'INICIO CARGA F_AGENDA_DETALHE'
	PRINT GETDATE()

		INSERT INTO F_AGENDA_DETALHE

			SELECT A.ID_AGENDA,
				   A.MATRICULA,
				   A.NOME_VEND,
				   A.RAZAO_SOCIAL,
				   A.DATA_VISITA,
				   A.SITUACAO,
				   1 QTD_VISITAS,
				   A.GEROU_VENDA 
			FROM MINICRM.DBO.V_CRM_AGENDAS_DETALHE A

	PRINT 'FIM CARGA F_AGENDA_DETALHE'
	PRINT GETDATE()

END