SELECT * FROM autor

INSERT INTO autor VALUES ('José Leon Machado','jose@gmail.com')
INSERT INTO autor VALUES ('Lenira Almeida Heck','lenira@gmail.com')
INSERT INTO autor VALUES ('Eliú Quintiliano','eliu@hotmail.com')
INSERT INTO autor VALUES ('Adelina Lopes Vieira','adelina@hotmail.com')
INSERT INTO autor VALUES ('Augusto Campos','augusto@gmail.com')
INSERT INTO autor VALUES ('F. S. Ribamar','ribamar@hotmail.com')
INSERT INTO autor VALUES ('Luiz Eduardo Borges','luizborges@globo.com')
INSERT INTO autor VALUES ('Mário Teza','mario@hotmail.com')
INSERT INTO autor VALUES ('Luiz Roberto Oliveira','luizoliveira@gmail.com')
INSERT INTO autor VALUES ('Mana Kuniyasu','mana@gmail.com')
INSERT INTO autor VALUES ('Sérgio Martins','sergio@globo.com')
INSERT INTO autor VALUES ('Donatello Grieco','donatello@gmail.com')
INSERT INTO autor VALUES ('Hermínio Bello de Carvalho','herminio@hotmail.com')
INSERT INTO autor VALUES ('Carlos Sandroni','carlos@gmail.com')
INSERT INTO autor VALUES ('Nina Rodrigues','nina@gmail.com')
INSERT INTO autor VALUES ('Didimo Agapito da Veiga Júnior','didimo@globo.com')
INSERT INTO autor VALUES ('Alisson Luiz Micoski','alisson@gmail.com')
INSERT INTO autor VALUES ('Hugo de Brito Machado','hugo@hotmail.com')
INSERT INTO autor VALUES ('Procuradoria Federal','procuradoria@gmail.com')
INSERT INTO autor VALUES ('Maria Jose','mariajose@gmail.com')