SELECT * FROM livro

INSERT INTO livro VALUES ('A Bruxa e o Caldeirão','35.2',50,1)
INSERT INTO livro VALUES ('A borboleta azul','70.4',5,1)
INSERT INTO livro VALUES ('Amanda e os Nanorobôs','211.2',69,1)
INSERT INTO livro VALUES ('Chuva e sol','15',100,1)
INSERT INTO livro VALUES ('O que é uma distribuição de Linux','75',36,2)
INSERT INTO livro VALUES ('PostgreSQL prático: versão 8.1.4','450',10,2)
INSERT INTO livro VALUES ('Python para desenvolvedores','80',120,2)
INSERT INTO livro VALUES ('Pão e Liberdade','75',62,2)
INSERT INTO livro VALUES ('O sol e o sal da zona sul','20.5',88,3)
INSERT INTO livro VALUES ('Olhares estrangeiros','86.3',33,3)
INSERT INTO livro VALUES ('Perspectivas para a nova MPB','152',69,3)
INSERT INTO livro VALUES ('Roteiro de Villa - Lobos','88.9',44,3)
INSERT INTO livro VALUES ('São Pixinguinha','56',3,3)
INSERT INTO livro VALUES ('Transformações do samba carioca no século XX','301.5',6,3)
INSERT INTO livro VALUES ('As raças humanas e a responsabilidade penal no Brasil','90.3',7,4)
INSERT INTO livro VALUES ('As servidões reais: estudo de direito civil (parte 1)','25',55,4)
INSERT INTO livro VALUES ('Aspectos destacados das associações privadas é  luz do código civil','69',18,4)
INSERT INTO livro VALUES ('Ação Penal como Instrumento de Coação nos Crimes Tributários','152',20,4)
INSERT INTO livro VALUES ('Boletim de direitos humanos','44',16,4)